# Generated by Django 4.2.7 on 2026-01-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modification_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times booking was modified'),
        ),
        migrations.AddField(
            model_name='booking',
            name='modified_at',
            field=models.DateTimeField(blank=True, help_text='Last modification date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_check_in',
            field=models.DateField(blank=True, help_text='Previous check-in date (for modifications)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_check_out',
            field=models.DateField(blank=True, help_text='Previous check-out date (for modifications)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(),
        ),
    ]
