# Generated by Django 4.2.7 on 2026-01-15 21:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_booking_modification_count_booking_modified_at_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('cleanliness_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=True, help_text='Admin can moderate reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_wishlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.CharField(choices=[('FLEXIBLE', 'Flexible - Free cancellation up to 24 hours before check-in'), ('MODERATE', 'Moderate - Free cancellation up to 5 days before check-in'), ('STRICT', 'Strict - 50% refund up to 1 week before check-in, no refund after'), ('NON_REFUNDABLE', 'Non-refundable - No refunds')], default='MODERATE', help_text='Cancellation policy for this property', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_refund_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage refund for cancellations (for custom policies)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map integration', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map integration', max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties_latitud_5ee5e3_idx'),
        ),
        migrations.AddField(
            model_name='propertywishlist',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertywishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Associated booking (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertywishlist',
            index=models.Index(fields=['user'], name='property_wi_user_id_4953d3_idx'),
        ),
        migrations.AddIndex(
            model_name='propertywishlist',
            index=models.Index(fields=['property'], name='property_wi_propert_e01825_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertywishlist',
            unique_together={('user', 'property')},
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['property', 'rating'], name='property_re_propert_2e4bae_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['user'], name='property_re_user_id_79dce1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['is_approved'], name='property_re_is_appr_9d4083_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyreview',
            unique_together={('property', 'user')},
        ),
    ]
